apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-flask-app
  labels:
    app: todo-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-flask-app
  template:
    metadata:
      labels:
        app: todo-flask-app
    spec:
      containers:
      - name: todo-flask-app
        image: ary289man/todo-flask-app:latest
        ports:
        - containerPort: 5001
        env:
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_PORT
          value: "27017"
        - name: FLASK_ENV
          value: "production"
        - name: PORT
          value: "5001"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-flask-app
spec:
  selector:
    app: todo-flask-app
  ports:
  - port: 80
    targetPort: 5001
  type: NodePort
