apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-flask-app
  labels:
    app: todo-flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-flask-app
  template:
    metadata:
      labels:
        app: todo-flask-app
    spec:
      containers:
        - name: todo-flask-app
          image: ary289man/todo-flask-app:latest
          ports:
            - containerPort: 5001
          env:
            - name: MONGO_HOST
              value: "mongodb"
            - name: MONGO_PORT
              value: "27017"
            - name: FLASK_ENV
              value: "production"
            - name: PORT
              value: "5001"
          resources:
            limits:
              memory: "512Mi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: todo-flask-app-service
spec:
  selector:
    app: todo-flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5001
  type: LoadBalancer
